In [1]:
import pandas as pd
import numpy as np
import acquire
import util
import pandas_profiling

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler

import warnings
warnings.filterwarnings('ignore')


In [2]:
df = acquire.get_titanic_data()

In [26]:
#pandas_profiling.ProfileReport(df)

Drop Columns:

    -I'm going to drop "deck" because it only has 203 columns out of 891

In [4]:
df.drop(columns=["deck"], inplace=True)

Fillna:

    -Do a consistent fill of missing values

In [28]:
df.fillna(np.nan, inplace=True)

Split:

    -Split the data into train and test sets

In [6]:
train, test = train_test_split(df, train_size=.8, random_state=123)

Impute:

    -fill the NANs with the mode value in embarked

In [7]:
imp_mode = SimpleImputer(missing_values=np.nan, strategy="most_frequent")

    -fit and transform train 
    
    -transform test

In [8]:
imp_mode.fit(train[["embarked"]])
train["embarked"] = imp_mode.transform(train[["embarked"]])
test["embarked"] = imp_mode.transform(test[["embarked"]])

In [9]:
train.embarked.value_counts()
test.embarked.value_counts()

S    129
C     40
Q     10
Name: embarked, dtype: int64

    -fill the NANs with the median value in age

In [10]:
imp_median = SimpleImputer(missing_values=np.nan, strategy="median")

In [11]:
train["age"] = imp_median.fit_transform(train[["age"]])

    -check to make sure there are no more NULL values in the age column


In [12]:
train.age.isnull().sum()

0

Encoding:

    -Integer Encoding
    
    -One hot encoder

    -create encoder

In [13]:
int_encoder = LabelEncoder()

    -fit to train set

In [14]:
int_encoder.fit(train.embarked)

LabelEncoder()

    -transform the "embarked" column data from letters to integers

In [15]:
train.embarked = int_encoder.transform(train.embarked)

    -check the counts of train

In [16]:
train.embarked.value_counts()

2    517
0    128
1     67
Name: embarked, dtype: int64

    -transform "embarked" into a np array

In [17]:
embarked_array = np.array(train.embarked)
embarked_array[0:5]

array([0, 1, 0, 1, 0])

    -transform "embarked" into a 2D array to feed to OneHot

In [18]:
embarked_array = embarked_array.reshape(len(embarked_array),1)

    -create OneHotEncoder

In [19]:
ohe = OneHotEncoder(sparse=False, categories="auto")

    -fit and transform to embarked_array

In [20]:
embarked_ohe = ohe.fit_transform(embarked_array)
embarked_ohe

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [21]:

test.embarked = int_encoder.transform(test.embarked)

    -transform test.embarked

In [23]:
embarked_array = np.array(test.embarked).reshape(len(test.embarked), 1)

    -transform embarked_array with OneHot

In [24]:
embarked_test_ohe = ohe.transform(embarked_array)

In [25]:
embarked_test_ohe[0:5]

array([[0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])